app:
  queue:
    kafka: "localhost:9092"

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: INFO

spring:
  jpa:
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"