app:
  name: Paywent
  id: pwt
  log-envs: false

pwt:
  queue:
    enabled: true

server:
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
  servlet:
    context-path: /

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    web:
      pageable:
        default-page-size: 15
        one-indexed-parameters: false
  datasource:
    connection-timeout: 60000
    leak-detection-threshold: 25000
    maximum-pool-size: 20
    jdbcUrl: jdbc:postgresql://localhost:5432/paywent?reWriteBatchedInserts=true&cachePrepStmts=true&useServerPrepStmts=true&stringtype=unspecified
    username: puser
    password: ${PG_PASSWORD:ppass}

springdoc:
  api-docs:
    enabled: false
    path: /openapi.yaml
  swagger-ui:
    url: /openapi.yaml
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    display-request-duration: true
    disable-swagger-default-url: true
