
### Post new profile #1
POST {{server}}/api/v1/profiles
Content-Type: application/json

{
  "name": "Markes"
}

### Post new profile #2
POST {{server}}/api/v1/profiles
Content-Type: application/json

{
  "name": "Julian"
}

### List all profiles
GET {{server}}/api/v1/profiles